name: fitnc_user
description: Fitness-Nc for user

publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_time_picker_spinner: ^2.0.0
  syncfusion_flutter_datepicker: ^19.3.43
  connectivity_plus: ^1.2.0
  oktoast: ^3.0.0
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.1
  firebase_auth: ^3.1.0
  firebase_storage: ^10.0.3
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  cloud_functions: ^3.0.5
  cloud_firestore: ^2.5.1
  date_picker_timeline: ^1.2.3
  loading_animations: ^2.2.0
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0
  fab_circular_menu: ^1.0.2
  get: ^4.3.8
  badges: ^2.0.1
  get_storage: ^2.0.3
  cron: ^0.3.2
  tuple: ^2.0.0
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
  firebase:
    path: ../fitnc_trainer/packages/firebase
  fitness_domain:
    path: ../fitnc_trainer/packages/fitness_domain
  intl: ^0.17.0
  camera: ^0.9.4+3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  lint: ^1.0.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/fitness_login_page/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/fitness_logo_3.png"